caltech101_template = [
    lambda c: f'a photo of a {c}.',
    lambda c: f'a painting of a {c}.',
    lambda c: f'a plastic {c}.',
    lambda c: f'a sculpture of a {c}.',
    lambda c: f'a sketch of a {c}.',
    lambda c: f'a tattoo of a {c}.',
    lambda c: f'a toy {c}.',
    lambda c: f'a rendition of a {c}.',
    lambda c: f'a embroidered {c}.',
    lambda c: f'a cartoon {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'a plushie {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'art of a {c}.',
    lambda c: f'graffiti of a {c}.',
    lambda c: f'a drawing of a {c}.',
    lambda c: f'a doodle of a {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a painting of the {c}.',
    lambda c: f'the plastic {c}.',
    lambda c: f'a sculpture of the {c}.',
    lambda c: f'a sketch of the {c}.',
    lambda c: f'a tattoo of the {c}.',
    lambda c: f'the toy {c}.',
    lambda c: f'a rendition of the {c}.',
    lambda c: f'the embroidered {c}.',
    lambda c: f'the cartoon {c}.',
    lambda c: f'the {c} in a video game.',
    lambda c: f'the plushie {c}.',
    lambda c: f'the origami {c}.',
    lambda c: f'art of the {c}.',
    lambda c: f'graffiti of the {c}.',
    lambda c: f'a drawing of the {c}.',
    lambda c: f'a doodle of the {c}.',
]